CREATE TABLE daily_anagram (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    puzzle_date DATE NOT NULL,
    letters VARCHAR(255) NOT NULL,
    CONSTRAINT uk_daily_anagram_puzzle_date UNIQUE (puzzle_date)
);

CREATE TABLE daily_anagram_solution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_anagram_id BIGINT NOT NULL,
    answer VARCHAR(255) NOT NULL,
    found BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_daily_anagram_solution_daily_anagram
        FOREIGN KEY (daily_anagram_id) REFERENCES daily_anagram (id),
    CONSTRAINT uk_daily_anagram_solution_answer UNIQUE (daily_anagram_id, answer)
);

CREATE INDEX idx_daily_anagram_solution_lookup
    ON daily_anagram_solution (daily_anagram_id, answer);
